### ISSUE TITLE
JasperReports 7 compatibility

### ISSUE THREAD

**Issue by Postremus** [pro-crafting/Jasper-report-maven-plugin#92]
JR 7 has just been released. https://repo1.maven.org/maven2/net/sf/jasperreports/jasperreports/7.0.0/
https://github.com/TIBCOSoftware/jasperreports/tree/release-7.0.0?tab=readme-ov-file#jasperreports-library-700-change-log

We should make sure this plugin is compatible with the newest version.

At least following tasks need to be done, in addition to some nice to haves:

- [x] Create branch for 3.6 releases, and bump the next version of main to 4.0.0-SNAPSHOT
- [x] Implement compatibility with JR 7 (#102)
- [x] (Optional, up for debate) Rename plugin to jasperreports-maven-plugin. Just fits other maven plugins better, and actually mentions this is a maven plugin. (#107)
- [x] (Optional, up for debate) Drop maven 3.5.2 support, only support 3.9 ?
-- Not going to drop maven 3.5.2 for now, since building reports with maven 4 seems to work fine.

**Comment by KeatsPeeks** [comment]
Hi, is there any progress or ETA on this issue ? Thanks.

**Comment by RainerGanss** [comment]
@Postremus Shouldn´t you be able to check the second box by definition? "Implement compatibility with JR 7" 
We are waiting for this release <3

**Comment by rturner-edjuster** [comment]
Comments on the "optional" items listed here:

**renaming:** I think it would make sense to follow the naming convention -- however, it will cause the artifact name to change -- no doubt causing confusion for users -- however, since you are bumping the major version to 4.0.0, it would be the right time to do it

**dropping Maven 3.5.2 support:** Many of the plugins require Maven 3.6.3 as a base -- moving the minimum to 3.9 might be a bit drastic unless you have a specific reason to do so -- I would suggest keeping at least 3.6.3 as a base minimum at least until Maven 4.0 is in wide use

BTW, any way anyone can help with "implement compatibility with JR 7" ? Do you have "more details" on what's needed to be done?

**Comment by RainerGanss** [comment]
@rturner-edjuster If you look at the title "JasperReports 7 compatibility" I think that is all this PR does to be honest.

**Comment by RainerGanss** [comment]
Oh, my bad. I thought this was an PR ... sorry for the mess

**Comment by stoufix** [comment]
> Hi, is there any progress or ETA on this issue ? Thanks.

i create a PR for this issue

**Comment by RainerGanss** [comment]
I was doing the same. So I can stop working on that. Thx!

**Comment by RainerGanss** [comment]
#102

**Comment by RainerGanss** [comment]
We´ll test the PR next Monday with our production reports. I´ll get back here.

**Comment by RainerGanss** [comment]
@rturner-edjuster @Postremus with respect to the optional renaming. If you do this, please consider providing the relocation information in the maven pom. 

https://maven.apache.org/guides/mini/guide-relocation.html

That way in maven central everyone can see, that the artefact was moved and where it moved to. It´s a bit tricky, since you have to publish a pom under the old group/arty-id with that relocation information. And 3.9 as a requirement is really quite harsh.

**Comment by stoufix** [comment]
> We´ll test the PR next Monday with our production reports. I´ll get back here.

Currently, I haven't found any issues related to this migration in the non-production environment. We are planning a load test in two weeks under production conditions. I will share the results here.
😉

**Comment by rturner-edjuster** [comment]
> @rturner-edjuster @Postremus with respect to the optional renaming. If you do this, please consider providing the relocation information in the maven pom.
> 
> https://maven.apache.org/guides/mini/guide-relocation.html
> 
> That way in maven central everyone can see, that the artefact was moved and where it moved to. It´s a bit tricky, since you have to publish a pom under the old group/arty-id with that relocation information. And 3.9 as a requirement is really quite harsh.

That would be up to @Postremus -- I was just commenting to provide feedback from a user. However, I agree with the suggestion of making it easier to map the transition.

**Comment by rturner-edjuster** [comment]
My local testing of @stoufix 's PR #102 is successful. Seems to work as expected.
@Postremus Are you able to comment on direction here? Do you want to make the other changes in your TODO list for this issue? (I can work on at least one of them and post a separate PR for it if you would like to do them.)

**Comment by RainerGanss** [comment]
@Postremus When are you planning und building a release for this?

**Comment by Postremus** [comment]
@RainerGanss I want to do some more sanity checks. Most likely I will build the release early next morning.
anway, closing this issue. All points done.

**Comment by Postremus** [comment]
@RainerGanss done
